### PR TITLE
Add README and Makefile

### PR DESCRIPTION
**Pull request by xiam**
This PR adds a README with instructions on how to use the Makefile to run the example.

### CODE REVIEW

**Review by ericharmeling — APPROVED** [review]
@xiam 

This is great! I really like having Makefiles to initialize the cluster. 

LGTM, but I have just one comment about the README instructions below.

**Comment by xiam** [comment]
@ericharmeling thanks! sorry, what's the comment about the README?

**Comment by ericharmeling** [comment]
> @ericharmeling thanks! sorry, what's the comment about the README?

Oops. Looks like my comment didn't go through. I was just requesting that we add a `go mod init hello-world-go-uppderdb` step before the `go run main.go` step for both insecure and secure examples, to get the dependencies.

**Comment by xiam** [comment]
@ericharmeling great suggestion! I ran these and committed `go.mod` and `go.sum` so the user does not have to.

**Comment by ericharmeling** [comment]
Thanks @xiam !

**Pull request merged**
